# Generated by Django 4.1.3 on 2022-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("NO_FILTER", "No Filter"),
                            ("COLORIZED", "Colorize"),
                            ("GRAYSCALE", "Grayscale"),
                            ("BLURRED", "Blurred"),
                            ("BINARY", "Binary"),
                            ("INVERT", "Invert"),
                        ],
                        max_length=500,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
